routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {
    /**
     * Dashboard
     */
    Route::get('/', 'DashboardController@index');

    /**
     * Project specific
     */
    Route::get('projects', 'ProjectsController@index');
    Route::get('projects/create', 'ProjectsController@create');
    Route::get('projects/{project}', 'ProjectsController@show');
    Route::post('projects', 'ProjectsController@store');

    /**
     * Project > Content
     */
    Route::post('projects/{project}/content/mass', 'MassContentController@store');
    Route::post('projects/{project}/content/upload', 'UploadController@store');
    Route::post('projects/{project}/content/download', 'ProjectDownloadController@download');
    Route::get('projects/{project}/content/create', 'ProjectContentController@create');
    Route::post('projects/{project}/content', 'ProjectContentController@store');
    Route::get('projects/{project}/content/{page}', 'ProjectContentController@show');
    Route::get('projects/{project}/content/{page}/edit', 'ProjectContentController@edit');
    Route::put('projects/{project}/content/{page}', 'ProjectContentController@update');
    Route::delete('projects/{project}/content/{page}', 'ProjectContentController@destroy');
    Route::put('projects/{project}/content/{page}/save', 'ProjectContentController@save');

    /**
     * Clients
     */
    Route::resource('clients', 'ClientsController');

    /**
     * Reports
     */
    Route::get('reports', 'ReportsController@index');

    /**
     * Users
     */
    Route::resource('users', 'UsersController');

    /**
     * System
     */
    Route::get('system', 'SystemController@index');
    Route::get('system/types', 'ProjectTypesController@index');
    Route::get('system/states', 'ProjectStagesController@index');

    /**
     * Websites
     */
    Route::get('websites', 'WebsitesController@index');
    Route::get('websites/create', 'WebsitesController@create');
    Route::post('websites', 'WebsitesController@store');

    /**
     * Search
     */
    Route::get('search', 'SearchController@index');

    /**
     * Profile
     */
    Route::get('profile', 'ProfileController@index');

    /**
     * Settings
     */
    Route::get('settings', 'SettingsController@index');

    /**
     * Changelog
     */
    Route::get('changelog', 'ChangelogController@index');
});

/**
 * Content Collection Routes
 */
Route::post('content/upload', 'UploadController@store');
Route::post('content/download', 'ContentDownloadController@download');
Route::get('content/{project}', 'ContentController@show');
Route::get('content/{project}/new-page', 'ContentController@create');
Route::get('content/{project}/{page}', 'ContentController@view');
Route::put('content/{project}/{page}', 'ContentController@update');
Route::post('content/{project}', 'ContentController@store');
Route::delete('content/{project}/{page}', 'ContentController@destroy');

/**
 * Login / Registration
 */
Auth::routes();

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $guarded = [];

    protected $dates = ['created_at', 'updated_at', 'due'];

    /**
     * Get the route key for the model.
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'permalink';
    }

    /**
     * Page relationship
     * @return object
     */
    public function pages()
    {
        return $this->hasMany('App\Page');
    }

    /**
     * Formatted due date
     * @return string
     */
    public function getFormattedDueDateAttribute()
    {
        return $this->due->format("F j, Y");
    }

    /**
     * Generate permalink
     * @return void
     */
    public function makePermalink()
    {
        $this->permalink = str_slug($this->name);
    }

    /**
     * Project permalink helper
     * @param  string $section URI Fragment
     * @return string
     */
    public function permalink($section = '')
    {
        if (substr($section, 0, 1) !== '/') {
            $section = '/' . $section;
        }

        return url('projects/' . $this->permalink . $section);
    }

    public function parentPages()
    {
        return $this->pages()->where('page_id', null)->get();
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;

class ProjectsController extends Controller
{
    public function index()
    {
        \Breadcrumbs::addCrumb('Projects', url('/projects'));

        $projects = Project::all();

        return view('projects.index', [
            'projects' => $projects,
        ]);
    }

    public function show(Project $project)
    {
        $this->breadcrumbs($project->title, url('/project/' . $project->permalink));

        return view('projects.show', [
            'project' => $project,
            'pages' => $project->parentPages(),
        ]);
    }

    public function create()
    {
        $this->breadcrumbs('New Project');

        return view('projects.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'type' => 'required',
            'client' => 'required',
        ]);

        Project::create([
            'title' => $request->input('title'),
            'client' => $request->input('client'),
            'description' => $request->input('scope'),
            'permalink' => str_slug($request->input('title')),
        ]);

        return redirect('projects')->with('status', 'Project Created!');
    }

    private function breadcrumbs($name, $url = '')
    {
        \Breadcrumbs::addCrumb('Projects', url('projects'));
        \Breadcrumbs::addCrumb($name, $url);
    }
}

resources/views/projects/create.blade.php
@extends('layouts.dashboard')

@push('scripts')
    <script src="{{ asset('tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('js/project.js') }}"></script>
@endpush

@section('content')
    <div class="project-header">
        <div class="container">
            <h2 class="title">New Project</h2>
            <a href="{{ url('projects') }}" class="btn-pill"><em class="fa fa-reply"></em> Return to List</a>
        </div>
    </div>

    @include('partials.msg.errors')

    <div class="content-builder">
        <div class="container">
            <form action="{{ url('projects') }}" method="post">
                {{ csrf_field() }}

                <div class="row">
                    <div class="content">
                        <div class="box">
                            <div class="form-field">
                                <label for="project-title">Project Title</label>
                                <input type="text" name="title" id="project-title" value="{{ old('title') }}">
                            </div>
                        </div>

                        <div class="box">
                            <div class="form-field">
                                <label for="project-scope">Scope of Work</label>
                                <textarea name="scope" class="editor" id="project-scope">{{ old('scope') }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="sidebar">
                        <button type="submit" class="btn full">Create Project</button>

                        <div class="widget">
                            <div class="form-field">
                                <label for="project-type"><em class="fa fa-tag"></em>Type</label>
                                <select name="type" id="project-type">
                                    <option value="">- Project Type -</option>
                                    <option{{ old('type') == 'Branding' ? ' selected' : '' }}>Branding</option>
                                    <option{{ old('type') == 'Design' ? ' selected' : '' }}>Design</option>
                                    <option{{ old('type') == 'Digital Ads' ? ' selected' : '' }}>Digital Ads</option>
                                    <option{{ old('type') == 'Marketing' ? ' selected' : '' }}>Marketing</option>
                                    <option{{ old('type') == 'Print' ? ' selected' : '' }}>Print</option>
                                    <option{{ old('type') == 'SEO / SEM' ? ' selected' : '' }}>SEO / SEM</option>
                                    <option{{ old('type') == 'Social' ? ' selected' : '' }}>Social</option>
                                    <option{{ old('type') == 'Website' ? ' selected' : '' }}>Website</option>
                                </select>
                            </div>
                        </div>

                        <div class="widget">
                            <div class="form-field">
                                <label for="project-client"><em class="fa fa-address-card-o"></em>Client</label>
                                <input type="text" name="client" id="project-client" value="{{ old('client') }}">
                            </div>
                        </div>

                        <div class="widget">
                            <div class="form-field">
                                <label for="project-stage"><em class="fa fa-list-ol"></em>Stage</label>
                                <select name="stage" id="project-stage">
                                    <option{{ old('stage') == 'Pending' ? ' selected' : '' }}>Pending</option>
                                    <option{{ old('stage') == 'Queued' ? ' selected' : '' }}>Queued</option>
                                    <option{{ old('stage') == 'Doing' ? ' selected' : '' }}>Doing</option>
                                    <option{{ old('stage') == 'Out for Proof' ? ' selected' : '' }}>Out for Proof</option>
                                    <option{{ old('stage') == 'Revisions' ? ' selected' : '' }}>Revisions</option>
                                    <option{{ old('stage') == 'Production Ready' ? ' selected' : '' }}>Production Ready</option>
                                    <option{{ old('stage') == 'Invoice' ? ' selected' : '' }}>Invoice</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="project-header">
        <div class="container">
            <h2 class="title">Projects</h2>
            <div class="project-actions">
                <a href="{{ url('projects/create') }}" class="btn"><em class="fa fa-plus"></em> New Project</a>
            </div>
        </div>
    </div>

    @include('partials.msg.success')

    <div class="project-feed">
        <div class="container">
            <!-- Filters (Type, Stage, Assignment) -->

            <div class="faux-table">
                <div class="faux-heading">
                    <div>Project Title</div>
                    <div>Budget</div>
                    <div>Deadline</div>
                    <div>Time Spent</div>
                    <div>Stage</div>
                    <div>Assigned to</div>
                </div>
                @foreach ($projects as $project)
                    <a href="{{ $project->permalink() }}" class="faux-row">
                        <div>
                            <span class="title">{{ $project->title }}</span><br>
                            {{ $project->client }}
                        </div>
                        <div>$6000</div>
                        <div>Sept 1, 2017</div>
                        <div>7 hours</div>
                        <div>Development</div>
                        <div></div>
                    </a>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.dashboard')

@push('scripts')
    <script src="{{ asset('js/project.js') }}"></script>
@endpush

@section('content')
    <div class="project-header">
        <div class="container">
            <div class="project-details">
                <h2 class="title">{{ $project->title }}</h2>
                <ul class="details">
                    <li>{{ $project->client }}</li>
                    <li>Stage: Development</li>
                    <li>Budget: $6,000</li>
                    @if (!is_null($project->due))
                        <li>Due: {{ $project->formatted_due_date }}</li>
                    @endif
                    <!-- <li class="archived"><em class="fa fa-folder-open-o"></em> Archived</li> -->
                </ul>
            </div>
            <div class="project-actions">
                <a href="#" class="btn-icon fa fa-bookmark-o" data-tooltip="Bookmark"></a>
                <a href="#" class="btn-icon fa fa-pencil" data-tooltip="Edit"></a>
                <a href="#" class="btn-icon fa fa-trash-o" data-tooltip="Delete"></a>
            </div>
        </div>
    </div>

    <div class="project-content">
        <div class="tab-wrapper">
            <ul class="tab-headings">
                <li class="tab"><a href="#overview">Overview</a></li>
                <li class="tab"><a href="#activity">Activity</a></li>
                @if ($project->description)
                <li class="tab"><a href="#scope">Scope of Work</a></li>
                @endif
                <li class="tab"><a href="#issues">Issues</a></li>
                <li class="tab"><a href="#proofs">Proofs</a></li>
                <li class="tab"><a href="#time">Time / Hours</a></li>
                <li class="tab active"><a href="#collection">Content</a></li>
                <li class="tab"><a href="#feedback">Feedback</a></li>
            </ul>
        </div>

        @include('partials.msg.success')

        <div class="tab-body" id="overview"></div>
        <div class="tab-body" id="activity"></div>
        @if ($project->description)
        <div class="tab-body" id="scope">
            {{ $project->description }}
        </div>
        @endif
        <div class="tab-body" id="issues"></div>
        <div class="tab-body" id="proofs"></div>
        <div class="tab-body" id="time"></div>
        <div class="tab-body active" id="collection">
            @if ($pages->count() > 0)
                <div class="row">
                    <div class="content">
                        <table class="table striped">
                            <tr>
                                <th class="mass-action"></th>
                                <th class="status"></th>
                                <th class="label">Title</th>
                                <th class="due">Deadline</th>
                                <th class="assigned">Assigned</th>
                                <th class="updated">Last Updated</th>
                                <th class="action"></th>
                            </tr>
                            @include('partials.page.list', ['pages' => $pages])
                        </table>
                    </div>
                    <div class="sidebar">
                        <a href="{{ $project->permalink('content/create') }}" class="btn full"><em class="fa fa-plus"></em>Add Section</a>
                        <button type="button" class="btn full" data-dialog="#multiple-pages"><em class="fa fa-files-o"></em>Create Multiple Sections</button>

                        <div class="widget">
                            <div class="form-field">
                                <label><em class="fa fa-paper-plane"></em>Send to Client</label>

                                <div class="form-group">
                                    <input type="text" value="{{ url('content/' . $project->permalink) }}" id="send-to-client" readonly>
                                    <button class="btn fa fa-link copy-to-clipboard" data-clipboard-target="#send-to-client"></button>
                                </div>
                            </div>
                        </div>

                        <!-- <div class="timeline">
                            <h3 class="headline">Activity</h3>
                            <ul class="feed">
                                <li class="entry">
                                    <div class="icon"></div>
                                    <div class="body">
                                        <div class="card">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis id, vel molestias quisquam inventore, rerum praesentium. Earum delectus est pariatur alias animi, dicta quas dolorem sint cum aliquid, expedita doloremque.</p>
                                            <time>Yesterday</time>
                                        </div>
                                    </div>
                                </li>
                                <li class="entry">
                                    <div class="icon"></div>
                                    <div class="body">
                                        <div class="card">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati fugit libero quod sed, quam tenetur incidunt nostrum maiores cum alias corporis expedita itaque, a, cumque consequatur officiis. Cupiditate, odit hic.</p>
                                            <time>Yesterday</time>
                                        </div>
                                    </div>
                                </li>
                                <li class="entry">
                                    <div class="icon"></div>
                                    <div class="body">
                                        <div class="card">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam architecto et magnam cum dolorum excepturi quos reiciendis culpa qui rem saepe similique impedit, repellat nesciunt officia officiis asperiores repudiandae. Nulla!</p>
                                            <time>Yesterday</time>
                                        </div>
                                    </div>
                                </li>
                                <li class="entry">
                                    <div class="icon"></div>
                                    <div class="body">
                                        <div class="card">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id aut laboriosam repudiandae, eum quam quod dolorem, placeat, minus sapiente nulla, alias officia explicabo distinctio! Iusto, voluptatibus, nesciunt! Autem, molestiae, harum?</p>
                                            <time>Yesterday</time>
                                        </div>
                                    </div>
                                </li>
                                <li class="entry">
                                    <div class="icon"></div>
                                    <div class="body">
                                        <div class="card">
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas suscipit placeat ullam error, commodi maxime rerum. Labore iste consequuntur mollitia voluptas voluptatibus asperiores in ut hic, aspernatur alias sed impedit?</p>
                                            <time>Yesterday</time>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <a href="#" class="view-all">View All Activity</a>
                        </div> -->
                    </div>
                </div>
            @else
                <div class="row">
                    <div class="full centered">
                        <div class="heading">
                            <h3>Get Started</h3>
                            <p>Provide a rough site structure to make organizing content easier.</p>
                        </div>
                        <p><a href="{{ $project->permalink('content/create') }}" class="btn large"><em class="fa fa-plus"></em>Add Section</a>
                        <button type="button" class="btn large" data-dialog="#multiple-pages"><em class="fa fa-files-o"></em>Create Multiple Sections</button></p>
                    </div>
                </div>
            @endif
        </div>
        <div class="tab-body" id="feedback"></div>
    </div>
@endsection

@section('footer-assets')
    <div id="multiple-pages" class="dialog">
        <div class="dialog-body">
            <form action="{{ url('/projects/' . $project->permalink . '/content/mass') }}" method="post">
                {{ csrf_field() }}
                <div class="dialog-header">
                    <h4 class="dialog-title">Create Multiple Sections</h4>
                    <button type="button" class="dialog-close"><em class="fa fa-times"></em></button>
                </div>
                <div class="dialog-content">
                    <div class="alert-errors hidden"></div>

                    <div class="form-field">
                        <label for="page-list">Structure</label>
                        <textarea name="pages" id="page-list" placeholder="Place each section on a new line"></textarea>
                        <p class="help">Use hyphens to indicate nested sections</p>
                    </div>
                    <div class="form-field">
                        <label for="deadline">Deadline</label>
                        <input type="text" name="deadline" id="deadline" class="datepicker">
                    </div>
                </div>
                <div class="dialog-footer">
                    <button type="submit" class="btn">Create Sections</button>
                </div>
            </form>
        </div>
    </div>
@endsection